# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'flying-ollama-model'
primary_region = 'lhr'

[build]
image = 'ollama/ollama'

[http_service]
internal_port = 11434
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[mounts]
source = "ollama_models"
destination = "/root/.ollama"

[[vm]]
cpu_kind = 'shared'
cpus = 4
memory = '4gb'
